Repository reacli/cli, pull requests merged in 2019-02, with the labels that each got.

#8 feat: add README about component architecture
  package-lock.json
  patterns/my-component/README.md
Labels: documentation

#10 fix: ignore some files in build
  .babelrc
  dist/CONTRIBUTING.md
  dist/README.md
  dist/commitlint.config.js
  package.json
Labels: enhancement

#16 Add a new parameter to integrate Redux snippets in the Container component
  bin/reacli.js
  dist/bin/reacli.js
  dist/patterns/my-component/components/MyComponentContainer.template
  patterns/my-component/components/MyComponentContainer.template
Labels: enhancement

#25 feat: add mustache and string-template for flow to compare them
  bin/reacli.js
  package-lock.json
  package.json
  patterns/my-component/components/MyComponent.template
  patterns/my-component/components/MyComponentContainer.template
Labels: enhancement

#30 Fix: put functions in separate files
  .gitattributes
  bin/reacli.js
  lib/core.js
  lib/flow.js
  lib/redux.js
  lib/utils/clean_up.js
  lib/utils/files.js
  lib/utils/validators.js
  package-lock.json
  package.json
Labels: project-structure

#33 Reacli config file (.reacli) to load project options
  bin/reacli.js
  lib/core.js
  package-lock.json
  package.json
Labels: enhancement

#35 Fix: changes current dir path
  lib/core.js
Labels: bug

#37 docs: bump version
  package.json
Labels: documentation

#42 fix: modify PR template to close issues on merges
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  package-lock.json
Labels: enhancement

#41 Use the CLI to create several components at once
  bin/reacli.js
  lib/core.js
  lib/utils/files.js
  lib/utils/validators.js
Labels: enhancement

#46 docs: bump version to 1.5.2
  package.json
Labels: documentation

#32 Added hooks template creation
  bin/reacli.js
  lib/core.js
  lib/utils/hookFiles.js
  package.json
  patterns/my-hook/hooks/MyHook.css
  patterns/my-hook/hooks/MyHook.template
  patterns/my-hook/index.template
Labels: enhancement, in review
