Repository reacli/cli, pull requests merged in 2019-03, with the labels that each got.

#43 Create an interactive, smart and more user-friendly CLI
  bin/reacli.js
  lib/core.js
  lib/interactiveCLI.js
  lib/utils/files.js
  lib/utils/hookFiles.js
  lib/utils/validators.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#56 Write integration tests
  .babelrc
  .travis.yml
  config/jest.config.js
  config/jest.init.js
  lib/core.js
  lib/flow.js
  lib/interactiveCLI.js
  lib/redux.js
  lib/utils/clean_up.js
  lib/utils/files.js
  lib/utils/hookFiles.js
  lib/utils/validators.js
  package.json
  test/common.js
  test/fixtures/combination-component/components/CombinationComponent.jsx
  test/fixtures/combination-component/components/CombinationComponent.scss
  test/fixtures/combination-component/components/CombinationComponentContainer.jsx
  test/fixtures/combination-component/index.js
  test/fixtures/flow-component/components/FlowComponent.css
  test/fixtures/flow-component/components/FlowComponent.jsx
  test/fixtures/flow-component/components/FlowComponentContainer.jsx
  test/fixtures/flow-component/index.js
  test/fixtures/pre-configured-component/components/PreConfiguredComponent.jsx
  test/fixtures/pre-configured-component/components/PreConfiguredComponent.scss
  test/fixtures/pre-configured-component/components/PreConfiguredComponentContainer.jsx
  test/fixtures/pre-configured-component/index.js
  test/fixtures/redux-component/components/ReduxComponent.css
  test/fixtures/redux-component/components/ReduxComponent.jsx
  test/fixtures/redux-component/components/ReduxComponentContainer.jsx
  test/fixtures/redux-component/index.js
  test/fixtures/scss-component/components/ScssComponent.jsx
  test/fixtures/scss-component/components/ScssComponent.scss
  test/fixtures/scss-component/components/ScssComponentContainer.jsx
  test/fixtures/scss-component/index.js
  test/fixtures/scss-hook/hooks/ScssHook.jsx
  test/fixtures/scss-hook/hooks/ScssHook.scss
  test/fixtures/scss-hook/index.js
  test/fixtures/simple-component/components/SimpleComponent.css
  test/fixtures/simple-component/components/SimpleComponent.jsx
  test/fixtures/simple-component/components/SimpleComponentContainer.jsx
  test/fixtures/simple-component/index.js
  test/fixtures/simple-hook/hooks/SimpleHook.css
  test/fixtures/simple-hook/hooks/SimpleHook.jsx
  test/fixtures/simple-hook/index.js
  test/integration-tests/component.test.js
  test/integration-tests/hook.test.js
  yarn.lock
Labels: enhancement, project-structure

#48 Add an option to ignore the Reacli configuration file
  .gitignore
  bin/reacli.js
  lib/core.js
  lib/interactiveCLI.js
Labels: enhancement, needs improvement

#61 fix: bump version to 1.6.3
  package.json
Labels: documentation

#62 Update the README.md and the CONTRIBUTING.md
  .README/img/interactiveCLI.png
  .travis.yml
  CONTRIBUTING.md
  README.md
Labels: documentation

#63 docs: bump version to 1.6.4
  package.json
Labels: documentation

#64 Image in README.md was broken
  .README/img/interactive-CLI.png
  .README/img/interactiveCLI.png
  .gitattributes
  README.md
  package.json
Labels: bug, documentation

#66 docs: add a MIT license to the project
  LICENSE.md
Labels: documentation

#67 fix: remove the question asked twice in interactive CLI
  lib/interactiveCLI.js
  package-lock.json
  package.json
Labels: bug

#68 Add terminal screencasts in README
  .README/img/basicUsage.svg
  .README/img/interactive-CLI.svg
  .gitattributes
  README.md
Labels: documentation, enhancement

#71 Improve the help output by the command-line tool
  README.md
  bin/reacli.js
  package.json
Labels: enhancement
